[package]
name = "atharva_refi"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "atharva_refi"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []
with-marinade = []


[dependencies]
anchor-lang = {version = "0.32.1", features = ["idl-build", "init-if-needed"] }
anchor-spl = { version = "0.32.1", features = ["idl-build"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
